## Robot Parameters
local_map_msg: "/octomap_tentabot"

# NOTE: Expected to be available in ROS paremeter server
#       by config files task_nav, map_utility
#world_frame_name: ""
#n_goal: 1
#goal1_x: 0.0
#goal1_y: 0.0
#goal1_z: 1.0
#goal1_yaw: 0.0
#world_name: ""
#robot_name: ""
#robot_frame_name: ""
#robot_bbx_x_min: 0.0
#robot_bbx_x_max: 0.0
#robot_bbx_y_min: 0.0
#robot_bbx_y_max: 0.0
#robot_bbx_z_min: 0.0
#robot_bbx_z_max: 0.0
#robot_max_lat_velo: 0.0
#robot_max_lat_acc: 0.0
#robot_max_yaw_velo: 0.0
#robot_max_yaw_acc: 0.0
#robot_odometry_msg: "/firefly/odometry_sensor1/odometry"
#robot_pose_control_msg: "/firefly/command/pose"
#robot_velo_control_msg: ""

## Process Parameters
visu_flag: true
time_limit: 150
dt: 0.01
goal_close_threshold: 0.5
ground_collision_flag: true
ground_collision_threshold: 0.05
#nav_data_path: "dataset/heuristic/firefly/"
drl_service_flag: false

mode: "testing"

## Trajectory Sampling Parameters
trajectory_sampling_dataset_path: "dataset/trajectory_sampling/kingfisher/"
tlen: 30
tsamp_cnt: 10

#trajectory_gen_type: "geometric"
#tyaw: 1.22173
#tpitch: 1.22173
#tyaw_cnt: 5
#tpitch_cnt: 5

trajectory_gen_type: "kinematic"
ttime: 10
lat_velo_samp_cnt: 9
ang_velo_samp_cnt: 9


## Offline Tuning Parameters
trajectory_data_path: ""
max_occupancy_belief_value: 100
sweight_max: 1
sweight_scale: 10
egrid_vdim: 0.1

pdist_x_min: -0.5
pdist_x_max: 0.5
pdist_y_min: -0.5
pdist_y_max: 0.5
pdist_z_min: -0.5
pdist_z_max: 0.5

sdist_x_min: -0.5
sdist_x_max: 0.5
sdist_y_min: -0.5
sdist_y_max: 0.5
sdist_z_min: -0.5
sdist_z_max: 0.5

## Online tuning Parameters
tbin_obs_cnt_threshold: 1
crash_dist_scale: 0.5
occupancy_scale: 3
close_scale: 50
smooth_scale: 30

### DRL Parameters
### NOTE: Be sure that -> drl_service_flag: true
### TODO: Add robot and task in openai_ros!