# AUTHOR: Neset Unver Akmandor (NUA)
#         Adrian J. Selva (AJS)
# E-MAIL: akmandor.n@northeastern.edu
#         selva.a@northeastern.edu

world_frame_name: "world"
map_name: "tentabot"
map_frame_name: "kingfisher"
map_resolution: 0.1
map_server_dt: 0.1

local_map_flag: false
dynamic_flag: false
skip_cnt_reset_sensor_range: 1

sensor_pc2_msg_name: "/kingfisher/pointcloud/filtered"
sensor_pc2_direction: "x"
sensor_pc2_min_range: 0.1
sensor_pc2_max_range: 100
sensor_pc2_max_yaw: 1.22173
sensor_pc2_max_pitch: 1.22173

# Based on physical parameters of robot
crop_x_min: -0.15
crop_x_max: 0.15
crop_y_min: -0.15
crop_y_max: 0.15
crop_z_min: -0.3
crop_z_max: 0.3

# Based on max sensor range of robot
bbx_x_min: -5
bbx_x_max: 5
bbx_y_min: -5
bbx_y_max: 5
bbx_z_min: -5
bbx_z_max: 5

filter_ground: false
filter_ground_threshold: 0.05